spring:
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: essm123456
    database: 0

  #数据源配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dept_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: dept_dev
    password: dept123456
    type: com.alibaba.druid.pool.DruidDataSource
    #2.0之后直接在这里配置数据库监控用户名密码。但是要加druid节点，上面
    druid:
      initialSize: 8
      minIdle: 8
      maxActive: 500
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      maxEvictableIdleTimeMillis: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid123

#mybatis配置
mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.xue.springcloud

#eureka-client端
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/
  instance:
    instance-id: cloud-zuul:9000 #服务别名配置
    prefer-ip-address: true #访问可以显示ip地址
    #心跳检测与续约时间（开发环境可以将值设小一点，保证服务关闭后注册中心能及时剔除）
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会遵循该规则）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳之后的等待的时间上限，单位为秒，超过就进行剔除（客户端告诉服务端自己会遵循该规则）
    lease-expiration-duration-in-seconds: 2

zuul:
  routes:
    dept-service:
      path: /dept-service/** #配置的转发路径
      serviceId: cloud-provider-dept #服务真实名称
  ignored-services: cloud-provider-dept #隐藏真实微服务名称，不让其访问

#info:
#  app.name: provider-dept:8001
#  company.name: xuexue
#  build.artifactId: @project.artifactId@
#  build.version: @project.version@

#热部署生效
#devtools:
#  restart:
#    enabled: true